In [2]:
print("Hi this is me trying")

Hi this is me trying

In [3]:
import pandas as pd
print("Pandas is ready!")

Pandas is ready!

In [4]:
data=({'Name':['Amit','Priya','Ravi','Sneha','Pooja'],"Department":['HR','IT','Finance','IT','HR'],"Salary":[45000,72000,61000,85000,39000],
       "City":['Mumbai','Bangalore','Delhi','Mumbai','Pune']})
df=pd.DataFrame(data)
print(df)

    Name Department  Salary       City
0   Amit         HR   45000     Mumbai
1  Priya         IT   72000  Bangalore
2   Ravi    Finance   61000      Delhi
3  Sneha         IT   85000     Mumbai
4  Pooja         HR   39000       Pune

In [5]:
df.head()

    Name Department  Salary       City
0   Amit         HR   45000     Mumbai
1  Priya         IT   72000  Bangalore
2   Ravi    Finance   61000      Delhi
3  Sneha         IT   85000     Mumbai
4  Pooja         HR   39000       Pune

In [6]:
df.shape

(5, 4)

In [7]:
df.columns

Index(['Name', 'Department', 'Salary', 'City'], dtype='object')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        5 non-null      object
 1   Department  5 non-null      object
 2   Salary      5 non-null      int64
 3   City        5 non-null      object
dtypes: int64(1), object(3)
memory usage: 292.0+ bytes

In [10]:
df['Salary'].sum()

np.int64(302000)

In [13]:
df['Salary'].mean()

np.float64(60400.0)

In [14]:
df['Salary'].max()

85000

In [15]:
df['Salary'].min()

39000

In [16]:
df['Salary'].count()

np.int64(5)

In [18]:
df.groupby("Department")["Salary"].sum()

Department
Finance     61000
HR          84000
IT         157000
Name: Salary, dtype: int64

In [19]:
df.groupby("Department")['Salary'].mean()

Department
Finance    61000.0
HR         42000.0
IT         78500.0
Name: Salary, dtype: float64

In [23]:
df.groupby("City")['Salary'].max()

City
Bangalore    72000
Delhi        61000
Mumbai       85000
Pune         39000
Name: Salary, dtype: int64

In [26]:
df.groupby("Department")['Name'].count()

Department
Finance    1
HR         2
IT         2
Name: Name, dtype: int64