In [ ]:
print("Hi this is me trying")

Hi this is me trying

In [20]:
import pandas as pd
print("Pandas is ready!")

Pandas is ready!

In [21]:
data=({'Name':['Amit','Priya','Ravi','Sneha','Pooja'],"Department":['HR','IT','Finance','IT','HR'],"Salary":[45000,72000,61000,85000,39000],
       "City":['Mumbai','Bangalore','Delhi','Mumbai','Pune']})
df=pd.DataFrame(data)
print(df)

    Name Department  Salary       City
0   Amit         HR   45000     Mumbai
1  Priya         IT   72000  Bangalore
2   Ravi    Finance   61000      Delhi
3  Sneha         IT   85000     Mumbai
4  Pooja         HR   39000       Pune

In [ ]:
df.head()

    Name Department  Salary       City
0   Amit         HR   45000     Mumbai
1  Priya         IT   72000  Bangalore
2   Ravi    Finance   61000      Delhi
3  Sneha         IT   85000     Mumbai
4  Pooja         HR   39000       Pune

In [ ]:
df.shape

(5, 4)

In [ ]:
df.columns

Index(['Name', 'Department', 'Salary', 'City'], dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        5 non-null      object
 1   Department  5 non-null      object
 2   Salary      5 non-null      int64
 3   City        5 non-null      object
dtypes: int64(1), object(3)
memory usage: 292.0+ bytes

In [ ]:
df['Salary'].sum()

np.int64(302000)

In [ ]:
df['Salary'].mean()

np.float64(60400.0)

In [ ]:
df['Salary'].max()

85000

In [ ]:
df['Salary'].min()

39000

In [ ]:
df['Salary'].count()

np.int64(5)

In [ ]:
df.groupby("Department")["Salary"].sum()

Department
Finance     61000
HR          84000
IT         157000
Name: Salary, dtype: int64

In [ ]:
df.groupby("Department")['Salary'].mean()

Department
Finance    61000.0
HR         42000.0
IT         78500.0
Name: Salary, dtype: float64

In [ ]:
df.groupby("City")['Salary'].max()

City
Bangalore    72000
Delhi        61000
Mumbai       85000
Pune         39000
Name: Salary, dtype: int64

In [ ]:
df.groupby("Department")['Name'].count()

Department
Finance    1
HR         2
IT         2
Name: Name, dtype: int64

In [7]:
df[df["Salary"]>60000]

    Name Department  Salary       City
1  Priya         IT   72000  Bangalore
2   Ravi    Finance   61000      Delhi
3  Sneha         IT   85000     Mumbai

In [11]:
df[df["City"] =="Mumbai"]

    Name Department  Salary    City
0   Amit         HR   45000  Mumbai
3  Sneha         IT   85000  Mumbai

In [10]:
df[df["Department"]=="IT"]

    Name Department  Salary       City
1  Priya         IT   72000  Bangalore
3  Sneha         IT   85000     Mumbai

In [12]:
df[(df["Salary"]>60000) & (df["City"]=="Mumbai")]

    Name Department  Salary    City
3  Sneha         IT   85000  Mumbai

In [16]:
df[(df["Department"] == "HR") | (df["City"] == "Delhi")]

    Name Department  Salary    City
0   Amit         HR   45000  Mumbai
2   Ravi    Finance   61000   Delhi
4  Pooja         HR   39000    Pune

In [17]:
df.sort_values("Salary")

    Name Department  Salary       City
4  Pooja         HR   39000       Pune
0   Amit         HR   45000     Mumbai
2   Ravi    Finance   61000      Delhi
1  Priya         IT   72000  Bangalore
3  Sneha         IT   85000     Mumbai

In [19]:
df.sort_values("Salary", ascending=False)

    Name Department  Salary       City
3  Sneha         IT   85000     Mumbai
1  Priya         IT   72000  Bangalore
2   Ravi    Finance   61000      Delhi
0   Amit         HR   45000     Mumbai
4  Pooja         HR   39000       Pune

In [22]:
df[["Name","Salary"]]

    Name  Salary
0   Amit   45000
1  Priya   72000
2   Ravi   61000
3  Sneha   85000
4  Pooja   39000

In [23]:
df["Department"].unique()

array(['HR', 'IT', 'Finance'], dtype=object)